# Generated by Django 5.2.6 on 2025-10-20 18:09

import collections
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0011_check_active_object_checks_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="params",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                dump_kwargs={"indent": 4},
                help_text="parameters needed to perform the check rvbuivrebiuvruvrervrejvrjvrjrve j9",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                verbose_name="parameters",
            ),
        ),
    ]
